# Solana Token 监听器配置文件
# 🔴 请根据实际需要修改以下配置 🔴

# Solana RPC节点配置
solana:
  # HTTP RPC节点列表 (支持多个节点，程序会自动切换)
  # WebSocket URL会自动从HTTP URL生成，无需手动配置
  # 建议修改为自己的专属节点，可在 Helius、Alchemy、Infura、Ankr、QuickNode 等提供商上免费注册
  http_urls:
    - "https://api.mainnet-beta.solana.com"
    - "https://solana-api.projectserum.com"
    - "https://rpc.ankr.com/solana"
    - "https://solana.public-rpc.com"

# 监听地址列表 (要监听的Solana钱包地址)
watch_addresses:
  - "2wVXwDnWUBoZqmFvFTMiUtMA5NZSvCtWBHgiEuHzBEd3"  # 示例1，修改为你要监听的地址
  - "zEftHcuc7jDHwGFVzDEBiAe8bhP8VuvRAE64ETwg6kZ"  # 示例2，修改为你要监听的地址
  # 你可以添加更多地址...

# Telegram机器人配置
telegram:
  # Telegram Bot Token (从 @BotFather 获取)
  bot_token: "123456789:ABCdefGHIjklMNOpqrsTUVwxyz"  # 示例，请替换为你的Bot Token
  
  # Telegram Chat ID (接收通知的聊天ID)
  chat_id: "9876543210"  # 示例，请替换为你的Chat ID


# 获取Telegram配置的步骤:
# ========================================
# 1. 在Telegram中搜索 @BotFather
# 2. 发送 /newbot 命令创建新机器人
# 3. 按提示设置机器人名称和用户名
# 4. 获得bot_token (格式: 123456789:ABCdefGHIjklMNOpqrsTUVwxyz)
# 5. 在Telegram中搜索 @userinfobot
# 6. 发送任意消息获得您的chat_id
# 7. 将bot_token和chat_id填入配置文件
#
# 测试配置:
# ========================================
# 1. 确保所有RPC节点可以正常访问
# 2. 确保Telegram机器人已创建并配置正确
# 3. 运行程序测试连接是否正常
# 4. 向监听地址发送少量Token测试通知功能 