# 这些是支持者链接。更多信息请访问：https://docs.github.com/articles/displaying-a-sponsor-button-in-your-repository

# 赞助者链接将显示在您的仓库页面上。
# 您最多可以添加 4 个赞助者链接，并且它们不能包含重复的赞助者类型。

github: # 用您的用户名替换
# patreon: # 或者用您的 Patreon 用户名替换
# open_collective: # 或者用您的 Open Collective 用户名替换
# ko_fi: # 或者用您的 Ko-fi 用户名替换
# tidelift: # 或者用您的 Tidelift 用户名替换
# community_bridge: # 或者用您的 Community Bridge 用户名替换
# liberapay: # 或者用您的 Liberapay 用户名替换
# issuehunt: # 或者用您的 IssueHunt 用户名替换
# otechie: # 或者用您的 Otechie 用户名替换
# custom: # 或者用自定义链接替换 